name: CICD

on:
  workflow_dispatch:


jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name:  Clone the code
        run: echo "cloning the code"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build using docker
        run: echo "Building using docker"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Running test cases
        run: echo "Testing the app"

        
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploying the machine
        run: echo "deploying the code"
      
